service:
  name: weather-forecast-aws

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  environment:
    WEBHOOK: ${opt:webhook}
custom:
  webpackIncludeModules: true
functions:
  weather-forecast:
    handler: app.weatherForecast
    events:
      - schedule: cron(0 22 * * ? *)
  weather-debug:
    handler: app.weatherForecast
    events:
      - http:
          method: get
          path: weatherdebug
