service:
  name: weather-forecast-aws

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  environment:
    WEBHOOK: ${opt:webhook}
custom:
  webpackIncludeModules: true
functions:
  weather-forecast-today:
    handler: app.weatherForecastToday
    events:
      - schedule: cron(30 22 * * ? *)
  weather-forecast-tomorrow:
    handler: app.weatherForecastTomorrow
    events:
      - schedule: cron(30 12 * * ? *)
  weather-debug-today:
    handler: app.weatherForecastToday
    events:
      - http:
          method: get
          path: debugtoday
  weather-debug-tomorrow:
    handler: app.weatherForecastTomorrow
    events:
      - http:
          method: get
          path: debugtomorrow
